# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oxygen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Oxygen
  pod 'SwiftLint', '~> 0.27'
  target 'OxygenUITests' do
    # Pods for testing
  end

  target 'OxygenUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
